// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(PayDBContext))]
    [Migration("20230518155218_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Bloc", b =>
                {
                    b.Property<int>("Idbloc")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDBloc")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NumarBloc")
                        .HasColumnType("int");

                    b.HasKey("Idbloc")
                        .HasName("PK__Bloc__3CFB8BB245FBCA1E");

                    b.ToTable("Bloc");
                });

            modelBuilder.Entity("API.Models.Judet", b =>
                {
                    b.Property<int>("Idjudet")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDJudet")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeJudet")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Idjudet")
                        .HasName("PK__Judet__D2AAE0672BBB57F3");

                    b.ToTable("Judet");
                });

            modelBuilder.Entity("API.Models.Locatii", b =>
                {
                    b.Property<int>("Idlocatii")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDLocatii")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bloc")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("Iduser")
                        .HasColumnName("IDUser")
                        .HasColumnType("int");

                    b.Property<string>("Judet")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("NrApometre")
                        .HasColumnType("int");

                    b.Property<int?>("NrLocatari")
                        .HasColumnType("int");

                    b.Property<string>("Oras")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Strada")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.HasKey("Idlocatii")
                        .HasName("PK__Locatii__6EB72DA768FBB044");

                    b.HasIndex("Iduser");

                    b.ToTable("Locatii");
                });

            modelBuilder.Entity("API.Models.Oras", b =>
                {
                    b.Property<int>("Idoras")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDOras")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeOras")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Idoras")
                        .HasName("PK__Oras__BA6D4AB46994EE18");

                    b.ToTable("Oras");
                });

            modelBuilder.Entity("API.Models.Strada", b =>
                {
                    b.Property<int>("Idstrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDStrada")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeStrada")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Idstrada")
                        .HasName("PK__Strada__A66FDE6924C83BA8");

                    b.ToTable("Strada");
                });

            modelBuilder.Entity("API.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnp")
                        .HasColumnName("cnp")
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Nume")
                        .HasColumnName("nume")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Parola")
                        .HasColumnName("parola")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14)
                        .IsUnicode(false);

                    b.Property<string>("Prenume")
                        .HasColumnName("prenume")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Telefon")
                        .HasColumnName("telefon")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("Tip")
                        .HasColumnName("tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilizator");
                });

            modelBuilder.Entity("API.Models.Locatii", b =>
                {
                    b.HasOne("API.Models.Utilizator", "IduserNavigation")
                        .WithMany("Locatii")
                        .HasForeignKey("Iduser")
                        .HasConstraintName("FK__Locatii__IDUser__398D8EEE")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
